version: '3.8'

services:
  # Main application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - search-network
    restart: unless-stopped

  # Elasticsearch service (optional - for full functionality)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - cluster.name=search-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - search-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  es-data:
    driver: local

networks:
  search-network:
    driver: bridge

# For lightweight deployment without Elasticsearch:
# docker-compose up app
# 
# For full deployment with Elasticsearch:
# docker-compose up
